### ISSUE TITLE
Hide or bypass User Account Control popup

### ISSUE THREAD

**Issue by umesh-m-jadhav** [rritoch/super-user-application#4]
Hi, 

I am extending my main class with SuperUserApplication and my jar is now running in administrator privileges. Thanks for this.

But the only annoying thing is "User account control popup"

After running the jar, I am getting "WARNING: Elevating an application with administrator privileges from a network or removable drive may fail." and after that I am getting the "User account control popup" with message "Do you want to allow the following program to make changes to this computer"

Is there any way to bypass or automatically hide this popup for better user experience?

Also instead of running whole jar in administrator privileges, is it possible to run the particular functionality of jar to be run in administrator privileges?

**Comment by umesh-m-jadhav** [comment]
Ralph,

Could you check above and answer please?

**Comment by rritoch** [comment]
umesh-m-jahav,

Hiding the UAC is an operating system setting and I don't believe Microsoft has documented any way to hide it with software.  You will get similar requests from other operating systems since this is a legitimate management tool and not a hacking tool. As for running part of the application without administrator privileges, it is possible since a thread could be made for unprivileged operations before control is passed to the security elevation code.  The privileged code will be running under its own process on the host operating system so short of using shared memory or third party data sharing privileged code will not have direct access to the unprivileged code or vice-versa.
